version: "3.9"
services:
  buyer:
    image: everlife-server-node:latest
    volumes:
      - ./everlifeai:/root/everlifeai
      - ./logs/buyer:/elife/logs
    environment:
      - ELIFE_NODE_NUM=5
      - ELIFE_STELLAR_HORIZON=test
  seller:
    image: everlife-server-node:latest
    volumes:
      - ./everlifeai:/root/everlifeai
      - ./logs/seller:/elife/logs
    environment:
      - ELIFE_NODE_NUM=6
      - ELIFE_STELLAR_HORIZON=test
